### ISSUE TITLE
1. Please specify the license. 2. How to run the code with my wav file and transcript? 

### ISSUE THREAD

**Issue by j-j-kam** [JazminVidal/gop-dnn-epadb#1]
Good day. Could you please indicate the license for your code, since I want to use it. 

I would also like to know how to compute the GOP score of my own wav file with the given text?

**Comment by JazminVidal** [comment]
Hi! The code and data are freely available for research and experimentation conditioned to citing the paper referenced in the readme file. 
The code is designed to work on Epa-DB. If you want to use your own wav files I suggest you to copy the format in which Epa-DB is used here which is, essentially, Kaldi standard format for preparing data. 

Thanks!

**Comment by j-j-kam** [comment]
@JazminVidal  thank you. what about commercial use?

**Comment by JazminVidal** [comment]
Hi, this specific repository is intended for experimentation on Epa-DB. 
For commercial use ask the original authors of the code at https://github.com/jimbozhang/kaldi-gop. 

Thanks!
