### ISSUE TITLE
03_compute.sh: no such path exp_epadb/test__/ivectors

### ISSUE THREAD

**Issue by j-j-kam** [JazminVidal/gop-dnn-epadb#2]
Good day. I'm successfully running the program until this moment: 

After running the 02 data preparation stage, here are the last messages:

Creating temporary folders for epadb files
/Users/myname/Desktop/epadb/test/
/Users/myname/Desktop/epadb/train/
done
Preparing data dirs
**cat: exp_epadb/corpus/test/*.lab: No such file or directory
cat: exp_epadb/corpus/train/*.lab: No such file or directory**
utils/fix_data_dir.sh: file exp_epadb/test__/utt2spk is not in sorted order or not unique, sorting it
utils/fix_data_dir.sh: file exp_epadb/test__/text is not in sorted order or not unique, sorting it
utils/fix_data_dir.sh: file exp_epadb/test__/wav.scp is not in sorted order or not unique, sorting it
fix_data_dir.sh: kept all        1 utterances.
fix_data_dir.sh: old files are kept in exp_epadb/test__/.backup
Extracting features
steps/make_mfcc.sh --nj 2 --mfcc-config conf/mfcc_hires.conf --cmd run.pl exp_epadb/test__
utils/validate_data_dir.sh: Successfully validated data-directory exp_epadb/test__
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
utils/split_scp.pl: You are splitting into too many pieces! [reduce $nj (2) to be smaller than the number of lines (1) in exp_epadb/test__/wav.scp]
steps/compute_cmvn_stats.sh exp_epadb/test__
steps/compute_cmvn_stats.sh: no such file exp_epadb/test__/feats.scp
fix_data_dir.sh: kept all        1 utterances.
fix_data_dir.sh: old files are kept in exp_epadb/test__/.backup
Extracting ivectors
steps/online/nnet2/extract_ivectors_online.sh --cmd run.pl --nj 1 exp_epadb/test__ 0013_librispeech_v1/exp/nnet3_cleaned/extractor exp_epadb/test__/ivectors
steps/online/nnet2/extract_ivectors_online.sh: No such file exp_epadb/test__/feats.scp
Finished data preparation and feature extraction!

But then, when I want to compute the GOP score finally, I get this message: 

**03_compute.sh: no such path exp_epadb/test__/ivectors**

How can it be fixed?

**Comment by JazminVidal** [comment]
Hi! 

I rerun the code and it ended successfully. I think you may be having trouble extractic features with your own data. Maybe is better if you try with more than one waveform. 

Thanks,
