### ISSUE TITLE
What exactly is data=exp_epadb ?

### ISSUE THREAD

**Issue by j-j-kam** [JazminVidal/gop-dnn-epadb#5]
Is it a directory I have to create myself? I know that there is an epadb directory, which is the database itself, but what is exp..?

**Comment by JazminVidal** [comment]
The directory in automatically created by the pipeline. Is where all the experiment (exp) results go. As the repository assumes experimentation on EpaDB the name is exp_epadb. So no, if you follow the pipeline it will be created on its own.
