### ISSUE TITLE
1. What is the difference between data_preparation.sh in the master folder and data_prep.py in epadb?

### ISSUE THREAD

**Issue by j-j-kam** [JazminVidal/gop-dnn-epadb#6]
2. If I process my own utterance and wav. , is the creation of annotations and .csv labels absolutely compulsory for a successful GOP scoring? I thought a wav. and a .lab were sufficient. I read your paper, but could not find evidence that annotations and labels were used for actual computation, it was rather done for general research purposes, wasn't it?

Thank you in advance. Your tool is fantastic, you've done an enormous effort that is appreciated.

**Comment by JazminVidal** [comment]
No, it is not. But you will need them to evaluate your results in case.
